version: '3.9'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres:5432/coodesh
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=coodesh
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: